name: Build and Deploy Personal Homepage  # Workflow name for identification

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the 'main' branch

permissions:
  contents: write  # Grant 'write' permission to repository contents for the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the build

    steps:
      - name: Checkout repository  # Step to check out the repository
        uses: actions/checkout@v3  # Use the v3 version of the actions/checkout action

      - name: Prepare Deploy  # Step to prepare deployment
        run: |
          mkdir deploy  # Create a directory named 'deploy'
          cp -R assets/ deploy/assets/  # Copy the 'assets' directory and its contents to 'deploy/assets/'
          cp index.html deploy/  # Copy the 'index.html' file to the 'deploy/' directory

      - name: Deploy to GitHub Pages  # Step to deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Use the v3 version of the peaceiris/actions-gh-pages action
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}  # Use the secret GITHUB_TOKEN for authentication
          publish_dir: ./deploy  # Specify the directory to publish: 'deploy/'
